version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-repository-procesos-ventas
    container_name: procesos-ventas-docker-nextjs-1
    ports:
      - "3004:3000"
    env_file:
      - .env
    networks:
      my_new_network:
        ipv4_address: 192.168.0.30  # Asigna una dirección IP dentro de esta subred

networks:
  my_new_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.169.0.0/24  # Ajusta la subred aquí
